[tools]
deno = ["2.5"]
java = ["25", "23", "21", "19", "17"]
maven = ["3"]
node = ["24"]
python = ["3.14", "3.10"]
rust = ["1.90"]
terraform = ["1.14.2", "1.12.1"]
yarn = ["4"]

[settings]
idiomatic_version_file_enable_tools = ["node"]
